"""
AttackPath model.

Represents an inferred attack path generated by the attack path inference
engine during scan post-processing.  Each path describes a sequence of steps
an attacker could take to compromise assets discovered in a
:class:`~app.models.scan.Scan`.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import ForeignKey, JSON, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.scan import Scan


class AttackPath(Base):
    """An inferred attack path linking multiple discovered assets.

    The attack path inference engine chains findings, services, and CVEs
    into plausible exploitation sequences and stores them here.

    Attributes:
        id: UUID primary key, auto-generated.
        scan_id: Foreign key to the parent :class:`~app.models.scan.Scan`.
        severity: Qualitative severity of the entire path (``critical``,
            ``high``, ``medium``, ``low``).
        title: Short human-readable title describing the attack scenario.
        steps: Ordered JSON list of attack steps, each describing an action,
            the targeted asset, and the prerequisite for the step.
        affected_nodes: JSON list of graph node IDs involved in this path,
            used to highlight the path in the interactive attack graph.
        scan: Parent :class:`~app.models.scan.Scan` relationship.
    """

    __tablename__ = "attack_paths"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    scan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("scans.id", ondelete="CASCADE"),
        nullable=False,
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )
    title: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )
    steps: Mapped[Optional[list]] = mapped_column(
        JSON,
        default=list,
        nullable=False,
        server_default="[]",
    )
    affected_nodes: Mapped[Optional[list]] = mapped_column(
        JSON,
        default=list,
        nullable=False,
        server_default="[]",
    )

    # -- Relationships ---------------------------------------------------------
    scan: Mapped[Scan] = relationship(
        "Scan",
        back_populates="attack_paths",
        lazy="joined",
    )

    def __repr__(self) -> str:
        return (
            f"<AttackPath {self.title!r} severity={self.severity!r} "
            f"scan_id={self.scan_id}>"
        )
