"""
Finding model.

Represents a prioritized security finding generated by the post-processing
pipeline (correlation engine + risk scoring) for a given
:class:`~app.models.scan.Scan`.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Float, ForeignKey, JSON, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.scan import Scan


class Finding(Base):
    """A security finding produced during scan post-processing.

    Findings aggregate evidence from multiple sources (subdomains, services,
    technologies, CVEs) into a single actionable item with a severity rating
    and weighted risk score.

    Attributes:
        id: UUID primary key, auto-generated.
        scan_id: Foreign key to the parent :class:`~app.models.scan.Scan`.
        severity: Qualitative severity label (``critical``, ``high``, ``medium``,
            ``low``, ``info``), indexed for efficient filtering.
        title: Short human-readable summary of the finding.
        description: Detailed explanation of the finding and its implications.
        asset: The affected asset identifier
            (e.g. ``staging.acme-corp.de:443``).
        risk_score: Weighted risk score computed by the risk scoring engine
            (0.0--100.0).
        cvss_score: Associated CVSS score if the finding is CVE-related.
        evidence: JSON blob with supporting evidence, raw data, and references.
        scan: Parent :class:`~app.models.scan.Scan` relationship.
    """

    __tablename__ = "findings"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    scan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("scans.id", ondelete="CASCADE"),
        nullable=False,
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    asset: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )
    risk_score: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )
    cvss_score: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )
    evidence: Mapped[Optional[dict]] = mapped_column(
        JSON,
        default=dict,
        nullable=False,
        server_default="{}",
    )

    # -- Relationships ---------------------------------------------------------
    scan: Mapped[Scan] = relationship(
        "Scan",
        back_populates="findings",
        lazy="joined",
    )

    def __repr__(self) -> str:
        return (
            f"<Finding {self.title!r} severity={self.severity!r} "
            f"risk_score={self.risk_score} scan_id={self.scan_id}>"
        )
